### ISSUE TITLE
How to randomize the noise?

### ISSUE THREAD

**Issue by rsautter** [caseman/noise#20]
Reading the code I found a commentary in simplex constructor, for new a pattern generation. However, every time I call the function with same parameters, the pattern is unchanged. How can I rerandomize the noise pattern?

So far, I tried to shift the window with a random value. Is it correct?
`mnoise = [[snoise2(4.0*float(m+random)/float(nt),5.0*float(n+random)/float(nt),16)
        for m in range(nt)]
        for n in range(nt)]`

**Comment by ianpdavies** [comment]
@rsautter Did this work out for you? I am trying this line of code you shared (assuming nt = freq, as in the snoise2 function details) but it is only returning a list of identical numbers.
