### ISSUE TITLE
README link to information on simplex noise is broken

### ISSUE THREAD

**Issue by tomjakubowski** [caseman/noise#23]
The README links to supplemental information on simplex noise: http://zach.in.tu-clausthal.de/teaching/cg2_08/literatur/simplexnoise.pdf

This link is broken: accessing the URL 404s. 

I dug around on the University of Bremen website (Schließlich sind Deutschkurse nützlich) and found what I think is the same document, but at a working URL: http://cgvr.cs.uni-bremen.de/teaching/cg_literatur/simplexnoise.pdf

However, even better than that, I think, is the annotated / corrected version from Stefan Gustavson himself, here http://staffwww.itn.liu.se/~stegu/simplexnoise/simplexnoise.pdf

**Comment by caseman** [comment]
Thanks for digging this up!

**Comment by caseman** [comment]
https://github.com/caseman/noise/commit/9c5d9e6262f8c83e9d6399733159573460f267e4
